# Workflow
# Should Have Name
name: Jimil

#on tells when the workflow will run
on: 
  workflow_dispatch: 
# Jobs tell what the workflow shoukd do  
# Should be inside the workflow
jobs: 
# 1st job give indentention
  say-Hello:
  # for short-term
    runs-on: ubuntu-latest
    steps:
     - name: Say hello to everyone
       run: echo "Hello dosto" 

# Steps
# Should be inide jobs

# Actions
# Should be inside the Steps
